#added by ATG for setup/sim launch
initial_joint_state: [-2.25,-1.16,-1.86,-1.67,1.58,0]
trajectory/seed_pose: [-2.25,-1.16,-1.86,-1.67,1.58,0]
#trajectory/seed_pose: [-2.25,-1.16,-1.86,-1.67,1.58,-2]
masking_tool_velocity: 20 # mm/s default 30

#-3.19
