# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.15
    has_acceleration_limits: false
    max_acceleration: 0
    min_position: 0.174533 #10
    max_position: 2.61799 #150
  shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 3.15
    has_acceleration_limits: false
    max_acceleration: 0
    min_position: -2.26893 #-130
    max_position: 0 #0
  shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 3.15
    has_acceleration_limits: false
    max_acceleration: 0
    #min_position: -1.22173 #-70
    #max_position: 1.5708 #90
  wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: false
    max_acceleration: 0
    #min_position: -3.14159 #-180
    #max_position: 0 #0
  wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: false
    max_acceleration: 0
    #min_position: -2.61799 #-150
    #max_position: 0 #0
  wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: false
    max_acceleration: 0
    ##min_position: -1.5708 #-90
    #min_position: 0 #0
    ##max_position: 2.44346 #140
    #max_position: 0.872665 #50
    min_position: 0
    max_position: 1.5708
