controller_list:
  - name: "" #"moveit_simple_controller_manager/MoveItSimpleControllerManager"
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
