manipulator:
  kinematics_solver: abb_irb1200_7_70_manipulator_kinematics/IKFastKinematicsPlugin
  kinematics_solver_attempts: 4
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
