<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="PI" value="3.14159265359"/>
   <!-- defining tool --><!-- Later, add collision models etc-->

  <!-- load tcp_params for tilt-->
  <xacro:property name="filename_tcp" value="$(find tool_model)/config/tcp_params.yaml" />
  <xacro:property name="tcp" value="${load_yaml(filename_tcp)}" />

  <!-- load tcp_params for tilt-->
  <xacro:property name="filename_tcp" value="$(find tool_model)/config/tcp_params.yaml" />
  <xacro:property name="tcp" value="${load_yaml(filename_tcp)}" />

  <!-- create a virutal link that is aligned actual tool orientation with robot controller -->
  <!--link name="controller_tool0"/>
  <joint name="controller_tool0_joint" type="fixed">
    <parent link="ee_link"/>
    <child link="controller_tool0"/>
    <origin xyz="0 0 0" rpy="${-PI/2} 0  ${-PI/2}"/>
  </joint-->

  <xacro:property name="L4" value="0.025"/>
  <xacro:property name="L3" value="0.04"/>
  <xacro:property name="L2" value="0.015"/>
  <xacro:property name="L1" value="0.005"/>
  <xacro:property name="TipZ" value="0.340"/>
  <!-- defining tool impedance tool EE3DOF-->
  <link name="tool_model">
    <visual>
      <geometry>
      <mesh filename="package://tool_model/meshes/EE3DOF.ply" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="LightGrey">
        <color rgba="0.7 0.7 0.7 1.0"/>
      </material>
    </visual>
    <visual>
      <geometry>
      <cylinder length="${L4}" radius="${0.04/2}"/>
      </geometry>
      <origin rpy="0 ${0} 0" xyz= "0 ${0} ${-L1-L2-L3-L4/2+TipZ}" />
      <material name="DarkGrey">
        <color rgba="0.3 0.3 0.3 1.0"/>
      </material>
    </visual>
    <visual>
      <geometry>
      <cylinder length="${L3}" radius="${0.02/2}"/>
      </geometry>
      <origin rpy="0 ${0} 0" xyz= "0 ${0} ${-L1-L2-L3/2+TipZ}" />
      <material name="DYellow">
        <color rgba="0.8 0.8 0.0 1.0"/>
      </material>
    </visual>
    <visual>
      <geometry>
      <cylinder length="${L2}" radius="${0.002/2}"/>
      </geometry>
      <origin rpy="0 ${0} 0" xyz= "0 ${0} ${-L1-L2/2+TipZ}" />
      <material name="LightGrey"/>
    </visual>
    <visual>
      <geometry>
      <cylinder length="${L1}" radius="${0.030/2}"/>
      </geometry>
      <origin rpy="0 ${0} 0" xyz= "0 ${0} ${-L1/2+TipZ}" />
      <material name="DarkGrey">
        <color rgba="0.3 0.3 0.3 1.0"/>
      </material>
    </visual>

  </link>
  <joint name="tool_model_joint" type="fixed">
    <parent link="controller_tool0" />
    <child link="tool_model" />
    <!--origin xyz="${0} ${0} ${0}" rpy="${0} ${PI} ${PI/4}"/-->
    <origin xyz="${tcp['eeX']} ${tcp['eeY']} ${tcp['eeZ']}"
            rpy="${tcp['eeR_']} ${tcp['eeP_']} ${tcp['eeY_']}"/>
  </joint>

  <!--xacro:property name="cyl_len" value="2"/-->
  <link name="tool"> <!-- will be used for last point calculation-->
    <!--collision>
      <geometry>
        <cylinder length="${cyl_len}" radius="${0.020/2}"/>
      </geometry>
      <origin rpy="1.5708 ${0} 0" xyz= "0 ${-cyl_len/2-0.05} ${-0.08}" />
    </collision-->
  </link>
  <!--xacro:include filename="$(find tool_model)/urdf/tcp_origin_viz.xacro" /-->

  <joint name="flange_to_tool" type="fixed">
          <parent link="controller_tool0" />
          <child link="tool" />
          <!--origin xyz="0 0.16 0.2165" rpy="0 0 0"/-->
          <origin xyz="${tcp['X']} ${tcp['Y']} ${tcp['Z']}"
                  rpy="${tcp['R_']} ${tcp['P_']} ${tcp['Y_']}"/>
  </joint>

  <disable_collisions link1="controller_tool0" link2="link6" reason="Adjacent" /> <!-- add this to srdf, its useless here-->
</robot>
