# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: false
    max_acceleration: 0
  shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: false
    max_acceleration: 0
  shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: false
    max_acceleration: 0
<<<<<<< HEAD
<<<<<<< HEAD
=======
    min_position: -0.35
    max_position: 2.79
>>>>>>> 9845d2bd0d7cd3b3d63106eb00234e3d05d9ac86
=======
    min_position: -0.35
    max_position: 2.79
>>>>>>> 07aca541621e5cba057452ac8435109ff36ed434
  wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 6.28
    has_acceleration_limits: false
    max_acceleration: 0
    min_position: -2.3569
    max_position: -0.7854
  wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 6.28
    has_acceleration_limits: false
    max_acceleration: 0
  wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 6.28
    has_acceleration_limits: false
    max_acceleration: 0
